conf/docker/web/docker_django/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('docker_django.apps.todo.urls')),
]

sms/urls.py
from django.conf.urls import url
import django_twilio
from . import views

urlpatterns = [
     url('checkcredit', views.get_credit),
]

sms/models.py
from django.db import models
class Credits(models.Model):
    date=models.DateTimeField(auto_now=True,)
    credits=models.CharField(max_length=50)
    class Meta:
            verbose_name = 'Uwazii SMS Credit'
            
class Sent_Sms(models.Model):
    date=models.DateTimeField(auto_now=False)
    phone_number=models.CharField(max_length=50,verbose_name="Phone Number")
    message_id=models.CharField(max_length=250,verbose_name="Message Id")
    
    class Meta:
            verbose_name = 'Sent sms'
            
class Starred_Sms(models.Model):
    date=models.DateTimeField(auto_now=False)
    error_code=models.CharField(max_length=50,verbose_name="Error code")
    error_description=models.CharField( max_length=50,verbose_name="Error description")
    mobile_number=models.CharField(max_length=50,verbose_name="Mobile Number")
    message_id =models.CharField(max_length=50,verbose_name="Message_Id")
    message=models.CharField(max_length=250)
    resent=models.BooleanField(default=False)
    Time_resent=models.CharField( max_length=50,verbose_name="Time resent",blank=True)            
    class Meta:
            verbose_name = 'Starred sms'

class Unsent_Sms(models.Model):
    date=models.DateTimeField(auto_now=False) 
    message= models.CharField(max_length=250)
    error =models.CharField(max_length=50)
    station = models.CharField(max_length=250)
    phone_number= models.CharField(max_length=250)
    resent=models.BooleanField(default=False)
    time_resent=models.CharField(max_length=50,verbose_name="Time resent",blank=True)
    
    class Meta:
            verbose_name = 'Unsent sms'

    

apps/checkout/views.py
from oscar.apps.checkout import views
from oscar.apps.payment import models 
from oscar.core.loading import get_model,get_class
from sms.views import send_sms
from sms.models import Unsent_Sms,Sent_Sms,Starred_Sms
Source=get_model("payment","Source")
SourceType=get_model("payment","SourceType")
import requests
# Subclass the core Oscar view so we can customise
class PaymentDetailsView(views.PaymentDetailsView):

    def handle_payment(self,order_number, total, **kwargs):
        amount = self.request.session['amount']
        receipt = self.request.session['receipt'] 
        phone_number = self.request.session['phone_number']
        message="Hi your order:{order_number} has been received by Roselian cakes.".format(**locals()) 
        # Talk to payment gateway.  If unsuccessful/error, raise a
        # PaymentError exception which we allow to percolate up to be caught
        # and handled by the core PaymentDetailsView.
        try:
            request=send_sms(phone_number,message)
            request=request.json()
            errorcode=request.get('ErrorCode')
            if errorcode==0:
                data=request.get('Data')[0]
                number=data.get('MobileNumber')
                message_id=data.get('MessageId')
                sent=Sent_Sms(phone_number=number,message_id=message_id)
                sent.save()
            else:
                error_code=request.get('ErrorCode')
                error_description=request.get('ErrorDescription')
                data=request.get('Data')[0]
                number=data.get('MobileNumber')
                message_id=data.get('MessageId')
                unsent=Starred_Sms(error_code=error_code,error_description=error_description,mobile_number=number,message_id=message_id,message=message)
                unsent.save()
        except Exception as e:
            unsent=Unsent_Sms(message=message,error=e,station="order",phone_number=number,)
        finally:   
            reference = receipt
            # # Payment successful! Record payment source
            source_type ,is_created=SourceType.objects.get_or_create(name="Lipa_Na_Mpesa")
            source =Source(
                source_type=source_type,
                amount_allocated=amount,
                reference=reference)
            self.add_payment_source(source)
            # Record payment event
            self.add_payment_event('pre-auth',amount,reference=reference)

templates/oscar/checkout/gateway.html
{% extends "oscar/checkout/layout.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
    {% trans "Checkout gateway" %} | {{ block.super }}
{% endblock %}
{% block checkout_title %}
<style>
.{
    display:flex;
    align-self:centre;
  
}
</style>
<div class="logo-container">
    <h1 style="color: #e41d1d;">Roselian cakes</h1>
    <h6 style="color:black;margin-top:-10px;">&nbsp;&nbsp;&nbsp; Indulge at your convinience</h6>
</div> 
<style>
.centre {
float: none;
position: absolute;
top: 8%;
left: 315px;
transform: translate(-50%, -50%);
}
</style>
<div class='centre'><!--centre logo at the middle of nav bar-->
    <a href="{{ homepage_url }}"><img src="{%static 'core/logo.png'%}" height="70" width='70'></a>
</div> 

<h1 style="margin-top:5%;">Who are you ?</h1>
{% endblock %}

{% block content %}
    
    <form method="post" class="form-stacked well">
        {% csrf_token %}
        {{ form.non_field_errors }}

        {% include "oscar/partials/form_field.html" with field=form.username %}

        <div class="form-group">
            <div class="controls">
                <div class="radio">
                    {{ form.options.0 }}
                </div>
            </div>
        </div>

        <div class="form-group {% if form.password.errors %}error{% endif %}">
            {{ form.options.errors }}
            <div class="controls">
                <div class="radio">
                    {{ form.options.2 }}
                    <div class="form-inline">
                        {% render_field form.password class+="form-control" %}
                        <small><a href="{% url 'password-reset' %}" tabindex="-1">{% trans "Get a password reminder" %}</a></small>
                        {% for error in form.password.errors %}
                            <span class="error-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="controls">
                <div class="radio">
                    {{ form.options.1 }}
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-lg btn-block btn-primary" data-loading-text="{% trans 'Continuing...' %}">{% trans "Continue" %}</button>
                </div>
            </div>
        </div>
    </form>

{% endblock content %}

{% block onbodyload %}
    {{ block.super }}
    oscar.checkout.gateway.init();
{% endblock %}

templates/oscar/checkout/layout.html
{% extends "oscar/layout.html" %}
{% load i18n %}
{% load category_tags %}
 <header class="header container-fluid">
     
{% block layout %}
    {% block navigation %}
          
    {% endblock %}

    <div class="container-fluid page">
       <div class="page_inner">              
            <div class="sub-header">
                <h1>{% block checkout_title %}{% endblock %}</h1>
            </div>
     
            <!-- The main nav on checkout pages contain links to modal flatpages -->
            {% block modal %}
                {% load flatpages %}
                {% get_flatpages '/order/' as flatpages %}
                {% for page in flatpages %}
                <div id="{{ page.title|slugify }}" class="modal hide fade">
                    <div class="modal-header">
                        <a class="close" data-dismiss="modal">×</a>
                        <h3>{{ page.title }}</h3>
                    </div>
                    <div class="modal-body">
                        <div class="large-content">
                            {{ page.content|safe }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endblock %}

            {% block content %}{% endblock %}

        </div><!-- /page_inner -->
    </div>
  
{% endblock %}

templates/oscar/checkout/new_address.html
{% load form_tags %}
{% load widget_tweaks %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% block new_address_form %}
        <form  method="post"  autocomplete='on' id="new_shipping_address" class="form form-horizontal" style="float:left;">
                {% csrf_token %}
                {% if form.is_bound and not form.is_valid %}
                    <div class="alert alert-danger">
                        <strong>Oops! We found some errors</strong> -please check the error messages below and try again
                    </div>
                {% endif %}

                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <i class="icon-exclamation-sign"></i> {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <label for="id_first_name" class="col-sm-4 control-label required">
                            name
                        </label>
                        <div class="col-sm-7">
                                <input type="text" name="first_name" maxlength="255" class="form-control" required id="id_first_name">
                                {% if field.errors %}
                                    <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                                {% endif %}
                        </div>
                </div> 
                {% include 'location.html'%}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <label for="id_line1" class="col-sm-4 control-label required">
                        Estate or building:
                    </label>
                    <div class="col-sm-7">
                        <input type="text" name="line1" maxlength="255" class="form-control" required id="id_line1">
                        {% if field.errors %}
                            <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                        {% endif %}
                    </div>
                </div>    
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <label for="id_phone_number" class="col-sm-4 control-label required" >
                        Phone number
                    </label>
                    <div class="col-sm-7">
                        <input type="text" name="phone_number" maxlength="128" class="form-control" placeholder="0712345678" required id="id_phone_number">
                        {% if field.errors %}
                            <span class="error-block"><i class="icon-exclamation-sign"></i>jiodjiojddniond</span>
                        {% endif %}
                        <span class='help-block'>
                            In case we need to call you about your order
                        </span>
                    </div>
                </div>
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <label for="id_notes" class="col-sm-4 control-label">
                        Instructions
                    </label>
                    <div class="col-sm-7">
                        <textarea name="notes" cols="40" rows="10" class="form-control" id="id_notes">
                        </textarea>
                        {% if field.errors %}
                            <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                        {% endif %}
                    <span class='help-block'>
                            Tell us anything we should know when delivering your order.Including a message or a note
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-lg btn-primary" data-loading-text="Continuing..." {% if addresses %}{%else%}onclick="submittotalForm(){% endif%}">Continue</button>
                        or"<a href="/basket/">return to basket</a>
                        <hr/>
                        <p style="color:blue;"><u>Risk whatever it takes to achieve your dream</u></p>
                    </div>
                </div>
            </form>
    {% endblock %}
{% endif %}

templates/oscar/checkout/shipping_address.html
{% extends "oscar/base.html" %}
{%load static %}
{% load i18n %}
{% load history_tags %}
{% load basket_tags %}
{% load currency_filters %}
{% load image_tags %}
{% load i18n %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/style.css' %}" />
    <link rel="stylesheet" href="{%static 'core/checkout/css/checkout.css'%}">

{% endblock %}

{% block layout %}
    <header class="header container-fluid"> 
        {% block navigation %}
            {% include "oscar/partials/nav_primary.html" %}
        {% endblock %}
    </header>
        {% include 'oscar/partials/alert_messages.html' %}
		<!-- checkout section  -->
		<section class="checkout-section spad">
			<div class="container">
				<div class="row">
					<div class="col-lg-3  col-md-4 col-sm-4 order-1 order-lg-2" style="margin-left:-1%;padding-right:10px;">
						<div class="checkout-cart">
							<h3><b><u>Your Cart</u></b></h3>
							<ul class="product-list">
								{% if request.basket.num_lines %}
								{% for line in request.basket.all_lines %}
								<li>
									<div class="pl-thumb">
									{% with image=line.product.primary_image %}
										{% oscar_thumbnail image.original "80x80" upscale=True as thumb %}
										<img  src="{{ thumb.url }}"  height=90px width=90px alt="{{ line.product.get_title }}">
										<h6 style="color:black;word-wrap:break-word;"><b><strong>{{ line.product.get_title }}</strong></b></h6>
										<h6>Quantity:Quantity:{{ line.quantity }}</h6>
										{% if line.is_tax_known %}
                                            <h6>price:{{ line.line_price_incl_tax|currency:line.price_currency }}</h6>
                                        {% else %}
                                            <h6>price:{{ line.line_price_excl_tax|currency:line.price_currency }}</h6>
                                        {% endif %}
									{% endwith %}
									</div>
								</li>
								{% endfor%}
								{% endif %}
							</ul>
							<ul class="price-list">
									{% if request.basket.is_tax_known %}
								<li class="">Cart total:<b>{{ request.basket.total_incl_tax|currency:request.basket.currency }}</b></h3>
									{% else%}
								<li class="">Cart total:<b>{{ request.basket.total_excl_tax|currency:request.basket.currency }}</b></h3>
									{% endif%} 
								<li class="">Shipping cost:<b>KSh</b><b id="shipping_cost">0.00</b></h3>
								<li class="total">Total:<u id="total_cost"></u></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 order-2 order-lg-1">
					    <div class="col-lg-8 col-md-8 col-sm-8  col-xs-12">
							<h2 style="float:centre;"><b><u>Shipping address</b></u></h2>	
							{% block shipping_address %}
								{% if user.is_authenticated %}
									{% if addresses %}
										<p>{% trans "An address from your address book?" %}</p>
												{% for address in addresses %}
													{% block select_address_form %}
														<div class="col-sm-6">
															<div class="well">
																<address>
																	{% block select_address_fields %}
																		{% for field in address.active_address_fields %}
																			<span>{{ field }}</span>{% if not forloop.first %}<br/>{% endif %}
																		{% endfor %}
																	{% endblock %}
																</address>
																<form action="{% url 'checkout:shipping-address' %}" method="post" id="select_shipping_address_{{ address.id }}">
																	{% csrf_token %}
																	<input type="hidden" name="action" value="ship_to" />
																	<input type="hidden" name="address_id" value="{{ address.id }}" />
																	{% if address.is_default_for_shipping %}
																		<button type="submit" class="btn btn-success btn-large ship-address" data-loading-text="{% trans 'Saving...' %}"><i class="icon-ok"></i> {% trans "Ship to your default shipping address" %}</button>
																	{% else %}
																		<button type="submit" class="btn btn-primary btn-large ship-address" data-loading-text="{% trans 'Saving...' %}">{% trans "Ship to this address" %}</button>
																	{% endif %}

																	<div class="btn-group address-controls">
																		<a href="{% url 'checkout:user-address-update' pk=address.id %}" class="btn btn-default btn-sm">{% trans "Edit address" %}</a>
																		<button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
																			<span class="caret"></span>
																		</button>
																		<ul class="dropdown-menu">
																			<li><a href="{% url 'checkout:user-address-delete' pk=address.id %}" class="btn-remove-address">{% trans "Delete" %}</a></li>
																		</ul>
																	</div>
																</form>
																<h3><a href="#" data-toggle="modal" data-target="#address_add">{% trans "Or a new address?" %}</a></h3>
																<div class="modal fade product_view" id="address_add">
																	<div class="modal-dialog">
																		<div class="modal-content">
																			<div class="modal-header">
																				<a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove"></span></a>
																				<a href="#" class="navbar-brand">
																				<h1>New Address </h1>
																				</a>
																			</div>
																			<div class="modal-body">
																				<form  method="post"  style="background-color:white;" autocomplete='on' id="new_shipping_address" class="form form-horizontal" style="float:left;">
																					{% csrf_token %}
																					<div class="form-group ">
																							<label for="id_first_name" class="col-sm-4 control-label required">
																								name
																							</label>
																							<div class="col-sm-7">
																									<input type="text" name="first_name" maxlength="255" class="form-control" required id="id_first_name">
																							</div>
																					</div> 
																					{% include 'location.html'%}
																					<div class="form-group ">
																						<label for="id_line1" class="col-sm-4 control-label required">
																							Estate or building:
																						</label>
																						<div class="col-sm-7">
																							<input type="text" name="line1" maxlength="255" class="form-control" required id="id_line1">
																						</div>
																					</div>    
																					<div class="form-group ">
																						<label for="id_phone_number" class="col-sm-4 control-label required" >
																							Phone number
																						</label>
																						<div class="col-sm-7">
																							<input type="text" name="phone_number" maxlength="128" class="form-control" placeholder="0712345678" required id="id_phone_number">
																							<span class='help-block'>
																								In case we need to call you about your order
																							</span>
																						</div>
																					</div>
																					<div class="form-group ">
																						<label for="id_notes" class="col-sm-4 control-label">
																							Instructions
																						</label>
																						<div class="col-sm-7">
																							<textarea name="notes" cols="40" rows="10" class="form-control" id="id_notes">
																							</textarea>
																							<span class='help-block'>
																								Tell us anything we should know when delivering your order.Including a message or a note
																							</span>
																						</div>
																					</div>
																					<div class="form-group">
																						<div class="col-sm-offset-4 col-sm-8">
																							<button type="submit" class="btn btn-lg btn-primary" data-loading-text="Continuing...">Continue</button>
																							or"<a href="/basket/">return to basket</a>
																							<hr/>
																							<p style="color:blue;"><u>Risk whatever it takes to achieve your dream</u></p>
																						</div>
																					</div>
																				</form>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														{% if forloop.counter|divisibleby:2 %}
														{% endif %}
													{% endblock %}
												{% endfor %}
									{% else %}
										{% include 'oscar/checkout/new_address.html'%}	
								    {% endif %}
							{% else %}
								{% include 'oscar/checkout/new_address.html'%}	
							{% endif %}
						</div>	
						<div class="col-lg-3 col-xs-12 col-md-12 col-sm-12 " style="background:rgb(253, 230, 230);">
							<h2><b><u>Shipping method</b></u></h2>
								<p><input type="radio" id="rdo-1" name="radio-grp" checked >Home and office delivery</p>
								<p><input type="radio" id="rdo-1" name="radio-grp" disabled >Pick up station<small style="color:red;">[comming soon]</small></p>
						</div>
						{% endblock shipping_address %}
					</div>
				</div>
			</div>
		</section>
	<form method="POST" action="/love" id="total_form">
		<input type="hidden" id="total" name="total" value="">
	</form>
	<script>
	function submittotalForm(){
		documents.getElementById('total_form').submit()

	}
	</script>
    {% include "oscar/partials/footer.html" %}
{% endblock %}

{# Local scripts #}
{% block scripts %}
    {{ block.super }}
    <!-- Twitter Bootstrap -->
    <script src="{% static 'core/js/bootstrap3/bootstrap.min.js' %}"></script>
    <script src="{%static 'core/checkout/js/jquery.steps.js'%}"></script>
    <script src="{%static 'core/checkout/js/checkout.js'%}"></script>

    <!-- Oscar -->
    <script src="{% static 'core/js/oscar/ui.js' %}"></script>
{% endblock %}

{% block extrascripts %}
    {% include "oscar/partials/extrascripts.html" %}
    {{ block.super }}
{% endblock %}

templates/oscar/checkout/shipping_methods.html
{% extends "oscar/checkout/checkout.html" %}

{% load currency_filters %}
{% load i18n %}
{% load shipping_tags %}

{% block title %}
    {% trans "Shipping method" %} | {{ block.super }}
{% endblock %}

{% block checkout_nav %}
    {% include 'oscar/checkout/nav.html' with step=2 %}
{% endblock %}

{% block checkout_title %}{% trans "Shipping method" %}{% endblock %}

{% block order_contents %}{% endblock %}
{% block shipping_address %}{% endblock %}
{% block payment_method %}{% endblock %}

{% block shipping_method %}
    <div class="basket-title">
        <div class="row">
            <h4 class="col-sm-8">{% trans "Method" %}</h4>
            <h4 class="col-sm-3">{% trans "Cost" %}</h4>
        </div>
    </div>
    {% for method in methods %}
        <div class="basket-items">
            <div class="row">
                <div class="col-sm-8">
                    <h4>{{ method.name }}</h4>
                    {% if method.description %}
                        <p>{{ method.description|safe }}</p>
                    {% endif %}
                    {% if method.is_discounted %}
                        <small>
                            {% shipping_charge_discount method basket as discount %}
                            {% blocktrans with amount=discount|currency:basket.currency name=method.discount_name %}
                                This includes a discount of <strong>{{ amount }}</strong> as
                                your basket qualifies for the <strong>{{ name }}</strong> offer.
                            {% endblocktrans %}
                        </small>
                    {% endif %}
                </div>
                <div class="col-sm-1">
                    {% shipping_charge method basket as charge %}
                    {% if charge.is_tax_known %}
                        {{ charge.incl_tax|currency:basket.currency }}
                    {% else %}
                        {{ charge.excl_tax|currency:basket.currency }}
                    {% endif %}
                </div>
                <div class="col-sm-3">
                    <form method="post" action="{% url 'checkout:shipping-method' %}">
                        {% csrf_token %}
                        <input type="hidden" name="method_code" value="{{ method.code }}" />
                        <button type="submit" class="btn btn-lg btn-primary pull-right" data-loading-text="{% trans 'Submitting...' %}">{% trans "Select option" %}</button>
                    </form>
                </div>    
            </div>
        </div>
    {% endfor %}
{% endblock shipping_method %}

templates/oscar/checkout/user_address_delete.html
{% extends "oscar/layout.html" %}
{% load i18n %}


{% block title %}
    {% trans "Delete address" %} | {{ block.super }}
{% endblock title %}

{% block content %}
<h1 syle="margin-left:30%;">Delete address</h1>

{% block shipping_address %}
    <form method="post" id="delete_address_{{ object.id }}">
        {% csrf_token %}
        <div class="well">
            <address>
                {% for field in object.active_address_fields %}
                    {{ field }}<br/>
                {% endfor %}
            </address>
        </div>
        <p>{% trans "Are you sure you want to delete this address?" %} <button type="submit" class="btn btn-danger" data-loading-text="{% trans 'Submitting...' %}">{% trans "Yes!" %}</button>
            {% trans "or" %} <a href="{% url 'checkout:shipping-address' %}">{% trans "cancel" %}</a>.</p>
    </form>
{% endblock shipping_address %}

{% endblock content %}

templates/oscar/checkout/user_address_form.html
{% extends "oscar/layout.html" %}
{% load i18n %}

{% block title %}
    {% trans "Edit address" %} | {{ block.super }}
{% endblock title %}
{% block content %}
<h1 syle="margin-left:30%;">Edit address</h1>

{% block shipping_address %}
    <div class="well">
        <form id="update_user_address" method="post" class="form form-horizontal">
            {% csrf_token %}
            {% include "oscar/partials/form_fields.html" with form=form style='horizontal' %}
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <button type="submit" class="btn btn-lg btn-primary" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button>
                    {% trans "or" %} <a href="{% url 'checkout:shipping-address' %}">{% trans "cancel" %}</a>.
                </div>
            </div>
        </form>
    </div>
{% endblock shipping_address %}
{% endblock content %}

templates/oscar/checkout/wait.html
{% load static %}
{% include 'oscar/partials/base_css.html'%}
<body>
<style>
/* This only works with JavaScript, 
if it's not present, don't show loader */
.no-js #loader { display: none;  }
.js #loader { display: block; position:fixed; left: 100px; top: 70%; }
.se-pre-con {
	position:fixed;
	left:40%;
	top:15%;
	width: 20%;
	height: 30%;
	background: url({%static 'core/checkout/images/loader.gif'%}) center no-repeat #fff;
}
</style>
<script>
// Wait for window load
$(window).load(function() {
    // Animate loader off screen
    $(".se-pre-con").fadeOut("slow");;
});

$('#modalPay').modal({
        show: 'false',
        backdrop: 'static',
        keyboard: false
    });
</script>
</div>
<!--Modal: modalPush-->
</body>
<div class="row">
  <div class="col-sm-9">
    <div class="button-wrap">
      <!-- Button trigger modal -->
    <div id="just_load_please">
        <div class="se-pre-con">Please enter your mpesa pin to make payment</div>
    </div>
    </div>
  </div>
</div>
<!-- Modal -->
<script>
$(document).ready(function() {
  $("#just_load_please").on("click", function(e) {
    e.preventDefault();
    $("#loadMe").modal({
      backdrop: "static", //remove ability to close modal with click
      keyboard: false, //remove option to close with keyboard
      show: true //Display loader!
    });
  });
  });
  //ajax code here (example for $.post) using test page from https://reqres.in
</script>
<style>
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'), local('Roboto-Light'), url(https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc9.ttf) format('truetype');
}
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxP.ttf) format('truetype');
}
body {
  height: 100%;
  padding: 0px;
  margin: 0px;
  background: #333;
  font-family: 'Roboto', sans-serif !important;
  font-size: 1em;
}
h1 {
  font-family: 'Roboto', sans-serif;
  font-size: 30px;
  color: #999;
  font-weight: 300;
  margin-bottom: 55px;
  margin-top: 45px;
  text-transform: uppercase;
}
h1 small {
  display: block;
  font-size: 18px;
  text-transform: none;
  letter-spacing: 1.5px;
  margin-top: 12px;
}
</style>